### PR TITLE
UPDATE: allow user-less deployments to rsync locations

### PR DESCRIPTION
**Pull request by stevie-mayhew**
Allows you to beam to locations based on SSH configuration which generally include user information.

### CODE REVIEW

**Comment by stevie-mayhew** [comment]
I haven't compiled the phar yet, can do that if needed but there are a few errors being thrown which would need to be merged into master first from the refactor @stecman is working on.

**Comment by stevie-mayhew** [comment]
Rebased :smile:

**Comment by stecman** [comment]
~~Thanks, @stevie-mayhew. I've merged the few updates and fixes sitting in the refactor branch and tested your changes. All good to merge once you've rebased against the updated master_~~ ...annd it's done. Ok, you get extra points for that.

If I was going to be super picky I'd probably say normalise/default the user value in the config to avoid `isset($server['user'])` propagating everywhere, but since I'm already in the middle of refactoring everything, I'll fix it later.

**Comment by stevie-mayhew** [comment]
Yay extra points! Thanks for doing the extra work for me :)

**Pull request merged**
